import { StyleSheet } from 'react-native';

export const authStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#070A0A',
  },
  backdropGlow: {
    position: 'absolute',
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: 'rgba(88, 201, 95, 0.12)',
    top: -80,
    right: -120,
  },
  backdropGlowSecondary: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(125, 251, 140, 0.10)',
    bottom: 120,
    left: -100,
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 32,
    gap: 20,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  brandBadge: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#151718',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(125, 251, 140, 0.16)',
  },
  brandTextWrap: {
    gap: 2,
  },
  brandLabel: {
    color: '#74F482',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.4,
  },
  brandSubLabel: {
    color: '#A7B2B5',
    fontSize: 12,
  },
  hero: {
    borderRadius: 28,
    padding: 22,
    backgroundColor: '#111617',
    borderWidth: 1,
    borderColor: 'rgba(125, 251, 140, 0.10)',
    gap: 14,
  },
  statusPill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#0C2108',
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#7DFB8C',
  },
  statusText: {
    color: '#7DFB8C',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
  },
  title: {
    color: '#F3F7F6',
    fontSize: 40,
    lineHeight: 42,
    fontWeight: '800',
  },
  subtitle: {
    color: '#B6C4C8',
    fontSize: 15,
    lineHeight: 22,
  },
  card: {
    backgroundColor: '#151718',
    borderRadius: 28,
    padding: 18,
    gap: 14,
    borderWidth: 1,
    borderColor: 'rgba(88, 201, 95, 0.12)',
  },
  sectionTitle: {
    color: '#F1F6F5',
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  fieldGroup: {
    gap: 8,
  },
  label: {
    color: '#A7B2B5',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  input: {
    backgroundColor: '#0C0E0F',
    color: '#F4F7F8',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#232829',
    fontSize: 16,
  },
  inputError: {
    borderColor: '#F26464',
  },
  helperText: {
    color: '#7A8582',
    fontSize: 12,
    lineHeight: 18,
  },
  errorText: {
    color: '#F28C8C',
    fontSize: 12,
    lineHeight: 18,
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#0C0E0F',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 16,
  },
  toggleTextWrap: {
    flex: 1,
    gap: 4,
  },
  toggleTitle: {
    color: '#F4F7F8',
    fontSize: 15,
    fontWeight: '700',
  },
  toggleDescription: {
    color: '#7A8582',
    fontSize: 12,
    lineHeight: 18,
  },
  primaryButton: {
    backgroundColor: '#58C95F',
    borderRadius: 18,
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  primaryButtonDisabled: {
    opacity: 0.65,
  },
  primaryButtonText: {
    color: '#07110A',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  secondaryButton: {
    backgroundColor: '#1B1F1C',
    borderRadius: 18,
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
    borderWidth: 1,
    borderColor: '#2B322D',
  },
  secondaryButtonText: {
    color: '#F4F7F8',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  footer: {
    alignItems: 'center',
    gap: 10,
    paddingBottom: 10,
  },
  footerText: {
    color: '#A7B2B5',
    fontSize: 13,
  },
  footerLink: {
    color: '#7DFB8C',
    fontSize: 14,
    fontWeight: '800',
  },
  biometricCard: {
    backgroundColor: '#0C2108',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(125, 251, 140, 0.14)',
    padding: 16,
    gap: 12,
  },
  biometricRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  biometricLabel: {
    color: '#E6F4EA',
    fontSize: 14,
    fontWeight: '800',
  },
  biometricDescription: {
    color: '#B9D8BF',
    fontSize: 12,
    lineHeight: 18,
  },
  biometricButton: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: 'rgba(125, 251, 140, 0.18)',
  },
  biometricButtonText: {
    color: '#F4F7F8',
    fontSize: 14,
    fontWeight: '800',
  },
});
