import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#070A0A',
  },
  container: {
    paddingHorizontal: 20,
    paddingBottom: 120,
    gap: 14,
  },
  containerCompact: {
    paddingHorizontal: 14,
  },
  topRow: {
    marginTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  brandRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  brandText: {
    color: '#74F482',
    fontWeight: '700',
    fontSize: 22,
  },
  systemOnline: {
    marginTop: 8,
    color: '#B6C4C8',
    letterSpacing: 2,
    fontSize: 11,
  },
  title: {
    color: '#F3F7F6',
    fontSize: 44,
    lineHeight: 46,
    fontWeight: '700',
  },
  titleCompact: {
    fontSize: 36,
    lineHeight: 38,
  },
  nodePill: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#121718',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 2,
  },
  dot: {
    width: 9,
    height: 9,
    borderRadius: 999,
    backgroundColor: '#7DFB8C',
    marginRight: 8,
  },
  nodePillText: {
    color: '#D9E3E4',
    fontSize: 14,
    fontWeight: '500',
  },
  heroCard: {
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: '#101414',
  },
  heroImageWrap: {
    minHeight: 208,
    justifyContent: 'flex-end',
  },
  heroImage: {
    borderRadius: 24,
  },
  heroShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(8,12,10,0.52)',
  },
  heroContent: {
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  heroSector: {
    color: '#78F88A',
    fontWeight: '800',
    fontSize: 30,
    lineHeight: 30,
  },
  heroLocation: {
    color: '#ECF5EF',
    fontWeight: '700',
    fontSize: 30,
    lineHeight: 30,
    marginTop: 2,
  },
  heroBody: {
    marginTop: 8,
    color: '#D6E2DA',
    fontSize: 14,
    lineHeight: 20,
    maxWidth: 220,
  },
  liveFeedButton: {
    backgroundColor: 'rgba(16,20,20,0.84)',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    alignSelf: 'flex-end',
  },
  liveFeedText: {
    color: '#EDF5F1',
    fontWeight: '600',
  },
  manualButton: {
    marginTop: 4,
    backgroundColor: '#58C95F',
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  autoButton: {
    backgroundColor: '#222526',
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  buttonLabel: {
    color: '#24572D',
    fontWeight: '800',
    fontSize: 11,
    letterSpacing: 1.5,
  },
  buttonLabelAuto: {
    color: '#81F395',
  },
  buttonTitle: {
    marginTop: 4,
    color: '#031406',
    fontSize: 30,
    fontWeight: '700',
  },
  buttonTitleDark: {
    marginTop: 4,
    color: '#EFF7F2',
    fontSize: 30,
    fontWeight: '700',
  },
  panel: {
    backgroundColor: '#151718',
    borderRadius: 24,
    padding: 16,
    gap: 12,
  },
  panelHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  panelTitle: {
    color: '#F0F4F3',
    fontWeight: '700',
    fontSize: 31,
  },
  onlineBadge: {
    backgroundColor: '#19351D',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  onlineText: {
    color: '#81F295',
    fontWeight: '700',
    fontSize: 10,
    letterSpacing: 1,
  },
  statusRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  metaLabel: {
    color: '#A7B2B5',
    fontSize: 13,
  },
  batteryText: {
    color: '#66ED7E',
    fontWeight: '700',
    fontSize: 46,
    lineHeight: 46,
  },
  batteryIconWrap: {
    backgroundColor: '#3A5140',
    borderRadius: 10,
    width: 110,
    height: 62,
    alignItems: 'center',
    justifyContent: 'center',
  },
  metaRow: {
    marginTop: 4,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  metaValue: {
    color: '#EFF4F2',
    fontSize: 22,
    fontWeight: '600',
  },
  signalValue: {
    color: '#BEE2FF',
  },
  telemetryItem: {
    backgroundColor: '#202324',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  telemetryLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  telemetryLabel: {
    color: '#EDF5F3',
    fontWeight: '500',
  },
  telemetryValue: {
    color: '#F4F7F8',
    fontWeight: '700',
  },
  kpiCard: {
    backgroundColor: '#0C0E0F',
    borderRadius: 22,
    padding: 16,
    gap: 6,
  },
  kpiLabel: {
    color: '#C2CFCD',
    fontSize: 13,
  },
  kpiValue: {
    color: '#F1F6F5',
    fontWeight: '700',
    fontSize: 37,
  },
});
