import { StyleSheet } from 'react-native';

export const remoteStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#070A0A',
  },
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  headerSection: {
    marginBottom: 24,
  },
  statusLabel: {
    color: '#7A8582',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.8,
    marginBottom: 8,
  },
  mainTitle: {
    color: '#FFFFFF',
    fontSize: 40,
    fontWeight: '700',
    lineHeight: 48,
    marginBottom: 16,
  },
  toggleContainer: {
    flexDirection: 'row',
    gap: 12,
  },
  toggleButton: {
    paddingHorizontal: 28,
    paddingVertical: 12,
    borderRadius: 24,
    minWidth: 80,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggleActive: {
    backgroundColor: '#58C95F',
  },
  toggleInactive: {
    backgroundColor: '#222526',
  },
  toggleText: {
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  toggleTextActive: {
    color: '#070A0A',
  },
  toggleTextInactive: {
    color: '#6C7473',
  },
  liveOperationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#0C2108',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    alignSelf: 'flex-start',
    marginTop: 16,
  },
  liveOperationDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#58C95F',
  },
  liveOperationText: {
    color: '#58C95F',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  liveTelemetryBadge: {
    backgroundColor: '#3D3D44',
  },
  liveTelemetryDot: {
    backgroundColor: '#E74C3C',
  },
  liveVideoContainer: {
    marginBottom: 20,
  },
  liveVideoBox: {
    backgroundColor: '#CCCCCC',
    borderRadius: 16,
    padding: 20,
    justifyContent: 'center',
    alignItems: 'center',
    height: 280,
    borderWidth: 3,
    borderColor: '#58C95F',
  },
  liveVideoLabel: {
    color: '#070A0A',
    fontSize: 16,
    fontWeight: '700',
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: '#58C95F',
    overflow: 'hidden',
  },
  manualTelemetryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 24,
  },
  manualTelemetryCard: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: '#151718',
    borderRadius: 12,
    padding: 16,
  },
  manualTelemetryLabel: {
    color: '#7A8582',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  manualTelemetryValue: {
    fontSize: 28,
    fontWeight: '700',
  },
  joystickSection: {
    alignItems: 'center',
    marginBottom: 24,
  },
  joystickDirectionLabel: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginBottom: 20,
  },
  joystickRing: {
    width: 240,
    height: 240,
    borderRadius: 120,
    borderWidth: 3,
    borderColor: '#2A2A2A',
    backgroundColor: '#151718',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    marginBottom: 24,
  },
  joystickRingLabel: {
    position: 'absolute',
    fontSize: 16,
    fontWeight: '700',
    color: '#6C7473',
  },
  joystickRingLabelTop: {
    top: 12,
  },
  joystickRingLabelBottom: {
    bottom: 12,
  },
  joystickRingLabelLeft: {
    left: 12,
  },
  joystickRingLabelRight: {
    right: 12,
  },
  joystickRingLabelActive: {
    color: '#58C95F',
  },
  joystickStick: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#58C95F',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    zIndex: 10,
  },
  joystickStickInner: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  joystickLabelsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 240,
  },
  joystickSideLabel: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  currentActionSection: {
    marginTop: 20,
    marginBottom: 20,
  },
  currentActionLabel: {
    color: '#7A8582',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  currentActionText: {
    color: '#FFFFFF',
    fontSize: 32,
    fontWeight: '700',
    marginBottom: 16,
    lineHeight: 40,
  },
  telemetryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 16,
  },
  telemetryCard: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: '#0C0E0F',
    borderRadius: 12,
    padding: 12,
  },
  telemetryLabel: {
    color: '#7A8582',
    fontSize: 9,
    fontWeight: '600',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  telemetryValue: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
  },
  neuralEngineSection: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  infoIcon: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#222526',
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoIconText: {
    color: '#58C95F',
    fontSize: 10,
    fontWeight: 'bold',
  },
  logEntryList: {
    backgroundColor: '#0C0E0F',
    borderRadius: 12,
    overflow: 'hidden',
  },
  logEntry: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#151718',
  },
  logEntryIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    marginTop: 2,
  },
  logEntryContent: {
    flex: 1,
  },
  logEntryTitle: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 4,
  },
  logEntrySubtitle: {
    color: '#7A8582',
    fontSize: 11,
    lineHeight: 15,
  },
  logEntryTime: {
    color: '#6C7473',
    fontSize: 10,
    marginTop: 4,
  },
  exportButton: {
    color: '#58C95F',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.3,
    marginTop: 8,
  },
  pathTrajectorySection: {
    marginBottom: 24,
  },
  chartContainer: {
    backgroundColor: '#0C0E0F',
    borderRadius: 12,
    height: 220,
    marginBottom: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chartPlaceholder: {
    color: '#6C7473',
    fontSize: 12,
  },
  chartLegend: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 16,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  legendText: {
    color: '#7A8582',
    fontSize: 11,
    fontWeight: '600',
  },
  energySection: {
    marginBottom: 24,
  },
  energyIcon: {
    alignItems: 'center',
    marginBottom: 12,
  },
  energyIconImage: {
    width: 40,
    height: 40,
  },
  energyTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 8,
    textAlign: 'center',
  },
  energyDescription: {
    color: '#7A8582',
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'center',
    marginBottom: 12,
  },
  energyBar: {
    backgroundColor: '#0C0E0F',
    borderRadius: 8,
    height: 8,
    marginBottom: 12,
    overflow: 'hidden',
  },
  energyBarFill: {
    backgroundColor: '#58C95F',
    height: '100%',
    width: '94%',
  },
  viewGridButton: {
    color: '#58C95F',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.3,
    textAlign: 'center',
  },
  // ===== LANDSCAPE MODE STYLES =====
  landscapeManualContainer: {
    flex: 1,
    position: 'relative',
    width: '100%',
    height: '100%',
  },
  landscapeVideoBackground: {
    flex: 1,
    backgroundColor: '#070A0A',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  landscapeVideoContent: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  landscapeVideoLabel: {
    color: '#070A0A',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: '#58C95F',
    overflow: 'hidden',
  },
  cameraHintText: {
    position: 'absolute',
    bottom: 100,
    color: '#58C95F',
    fontSize: 12,
    fontWeight: '600',
    opacity: 0.7,
  },
  landscapeJoystickContainer: {
    position: 'absolute',
    bottom: 12,
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 20,
  },
  landscapeJoystickRing: {
    width: 180,
    height: 180,
    borderRadius: 90,
    borderWidth: 3,
    borderColor: '#2A2A2A',
    backgroundColor: '#151718',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  landscapeJoystickStick: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#58C95F',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    zIndex: 10,
  },
  landscapeDirectionLabel: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#151718',
    borderRadius: 12,
  },
  landscapeTelemetryBox: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: '#151718',
    borderRadius: 12,
    padding: 12,
    minWidth: 120,
    zIndex: 15,
  },
  landscapeTelemetryItem: {
    marginBottom: 10,
  },
  landscapeTelemetryLabel: {
    color: '#7A8582',
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 0.3,
    marginBottom: 4,
  },
  landscapeTelemetryValue: {
    fontSize: 20,
    fontWeight: '700',
  },
  // ===== GYRO CONTROL STYLES =====
  gyroControlSection: {
    alignItems: 'center',
    marginBottom: 20,
    gap: 8,
  },
  gyroButton: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 2,
  },
  gyroButtonActive: {
    backgroundColor: '#58C95F',
    borderColor: '#58C95F',
  },
  gyroButtonInactive: {
    backgroundColor: 'transparent',
    borderColor: '#58C95F',
  },
  gyroButtonText: {
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  gyroButtonTextActive: {
    color: '#070A0A',
  },
  gyroButtonTextInactive: {
    color: '#58C95F',
  },
  gyroStatusText: {
    color: '#81F295',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
});
