[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM4
upload_speed = 460800
upload_protocol = esptool
upload_flags =
  --before
  default_reset
  --after
  hard_reset
monitor_port = COM4
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson @ ^7.0.4
  sparkfun/SparkFun SGP30 Arduino Library @ ^1.0.5
  levkovigor/LTR390 @ ^1.0.0
  https://github.com/wemos/WEMOS_SHT3X_Arduino_Library.git
  adafruit/Adafruit SSD1306 @ ^2.5.7
  adafruit/Adafruit GFX Library @ ^1.11.9
build_flags =
  -DAPP_NAME=\"AGRIBOT-ESP32\"
